version: '3'
services:
 
  haproxy_nginx:
    image: harshit05/docker-challenge-solved-harshit
    ports:
      - "80:80"

  metrics_scraper:
    build:
      context: ./scraper  # Build from the 'scraper' directory
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - haproxy_nginx
